
-- RentaCar - Creacion de tablas
-- Orden de creacion: tablas maestras primero, Reserva al final

CREATE TABLE Auto (
    id_placa        VARCHAR2(6)  PRIMARY KEY,
    marca           VARCHAR2(40) NOT NULL,
    modelo          VARCHAR2(40) NOT NULL,
    anio            NUMBER(4)    NOT NULL,
    disponibilidad  CHAR(1)      NOT NULL
                    CHECK (disponibilidad IN ('S','N'))
);

CREATE TABLE Client (
    cliente_id           VARCHAR2(20)  PRIMARY KEY, -- cedula o pasaporte
    nombre               VARCHAR2(50)  NOT NULL,
    apellido             VARCHAR2(50)  NOT NULL,
    telefono_celular     VARCHAR2(20)  NOT NULL,
    correo_electronico   VARCHAR2(320) NOT NULL
);

CREATE TABLE Cajero (
    id_cajero   VARCHAR2(20) PRIMARY KEY, -- cedula o pasaporte
    nombre      VARCHAR2(50) NOT NULL,
    apellido    VARCHAR2(50) NOT NULL
);

CREATE TABLE Pagos (
    pagos_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo_pago    VARCHAR2(20) NOT NULL
                   CHECK (metodo_pago IN ('TARJETA','EFECTIVO','ACH')),
    tipo_tarjeta   VARCHAR2(30) NULL, -- solo aplica si metodo_pago = 'TARJETA'
    monto          NUMBER(7,2)  NOT NULL
);

CREATE TABLE Reserva (
    reserva_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pagos_id         NUMBER        NOT NULL,
    id_placa         VARCHAR2(6)   NOT NULL,
    id_cajero        VARCHAR2(20)  NOT NULL,
    cliente_id       VARCHAR2(20)  NOT NULL,
    fecha_salida     DATE          NOT NULL,
    fecha_entrega    DATE          NOT NULL,
    cargo_tardanza   NUMBER(5,2)   NOT NULL,

    CONSTRAINT fk_reserva_pago    FOREIGN KEY (pagos_id)   REFERENCES Pagos(pagos_id),
    CONSTRAINT fk_reserva_auto    FOREIGN KEY (id_placa)   REFERENCES Auto(id_placa),
    CONSTRAINT fk_reserva_cajero  FOREIGN KEY (id_cajero)  REFERENCES Cajero(id_cajero),
    CONSTRAINT fk_reserva_client  FOREIGN KEY (cliente_id) REFERENCES Client(cliente_id)
);
